#!/bin/bash


LLVMM_DIR=~/.llvmm
mkdir -p ${LLVMM_DIR}/default

MACHINE_ARCH=$(uname -m)
SUPPORTED_ARCHS=( x86_64 arm64 )
SUPPORTED_OS=( darwin rhel ubuntu fedora )

TARGET_OS=""
TARGET_ARCH=""

resolve_system() {
    local sys_name
    sys_name=$(uname -a)
    
    for os in "${SUPPORTED_OS[@]}"
    do
        if [[ $sys_name == *$os* ]]
        then
            TARGET_OS=$os
        fi
    done
}

resolve_system
if [[ $TARGET_OS == "" ]]
then
    echo "Seems like your OS is not supported yet :/"
    exit 1
fi

resolve_arch() {
    for arch in "${SUPPORTED_ARCHS[@]}"
    do
        if [[ $MACHINE_ARCH == "$arch" ]]
        then
            TARGET_ARCH=$arch
        fi
    done
}

resolve_arch
if [[ $TARGET_ARCH == "" ]]
then
    echo "Seems like your arch is not supported yet :/"
    exit 1
fi


ls_remote() {
    local remote_versions=$( curl -s 'https://api.github.com/repos/llvm/llvm-project/releases?per_page=100' | jq '.[].name' )
    
    for r_version in ${remote_versions}
    do
        if [[ $r_version == *LLVM* ]]
        then
            continue
        fi
        
        local version=${r_version:0:-1}
        
        printf "%20s\n" "$version"
    done
}


list() {
    for f in "${LLVMM_DIR}"/*
    do [ -d "$f" ]
        if [[ $f == *default* ]]
        then
            continue
        fi
        
        printf "%20s\n" "v$version"
    done
}


is_installed() {
    local version=$1
    
    if [[ $version == "" ]]
    then
        echo "should provide a version"
    fi
    
    for f in "${LLVMM_DIR}"/*
    do [ -d "$f" ]
        if [[ $f == *default* ]]
        then
            continue
        elif [[  $f == *$version*  ]]
        then
            return 0 # is installed
        fi
    done
    
    return 1 # is not installed
}


remove () {
    local version=$1
    
    if [[ $version == "" ]]
    then
        echo "should provide a version"
    fi
    
    is_installed "${version}"
    rc=$?
    
    if [ $rc -eq 0 ]
    then
        rm -r "${LLVMM_DIR}/${version:?}"
        rc=$?
        
        echo "version ${1} successifully removed"
        return 0
    else
        echo "the version '${version}' is not installed"
        return 1
    fi
}

version_exists() {
    local candidate_version=$1
    if [ -z "$candidate_version" ]
    then
        echo "should specify a version"
        exit 1
    fi
    
    local remote_versions
    remote_versions=$( curl -s 'https://api.github.com/repos/llvm/llvm-project/releases?per_page=100' | jq '.[].name' )
    
    for r_version in ${remote_versions}
    do
        if [[ $r_version == *LLVM* ]]
        then
            continue
        fi
        
        local version=${r_version:0:-1}
        
        if [[ $version == "$candidate_version" ]]
        then
            return 0
        fi
    done
    
    echo "the selected version does not exists"
    return 1
}

install() {
    local version
    version=$1
    version_exists "$version"
    
    echo $?
}

build_from_source() {
    echo ""
}

make_default() {
    echo ""
}



OPTION=$1
OPTION_ARG1=$2

case $OPTION in
    "remove"|"rm")
        remove "${OPTION_ARG1}"
    ;;
    "ls-remote"|"remote")
        ls_remote
    ;;
    "ls"|"local")
        list
    ;;
    "install"|"i")
        install "${OPTION_ARG1}"
    ;;
    "default"|"d")
        echo "default"
    ;;
    *);;
esac
